image: node:14.13.0

clone:
  depth: full

definitions:
  docker:
    memory: 4096
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node
          - sonar
        script:
          #- yarn add global jest
          - yarn install --silent
          - yarn test
          - pipe: sonarsource/sonarcloud-scan:1.2.1
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              SONAR_SCANNER_OPTS: -Xmx4096m
              EXTRA_ARGS: '-Dsonar.sources=src -Dsonar.tests=src/tests -Dsonar.test.inclusions="**/tests/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
pipelines:
  default:
    - step: *build-test-sonarcloud
  pull-requests:
    "**":
      - step: *build-test-sonarcloud
