service: "resources-data-event-logger"
frameworkVersion: ">=1.8.0"

enableLocalInstallationFallback: true

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-offline
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  prune:
    automcatic: true
    number: 1

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  - ${file(src/functions/resource-data-event-logger.yml)}
